### ISSUE TITLE
[bug] Mod not compatible with Snapshot 20w51a

### ISSUE THREAD

**Issue by HeyItsJono** [Siphalor/mouse-wheelie#101]
**Version**
Snapshot 20w51a
**Describe the bug**
Game fails to start when mod is enabled; using version 1.6.1+mc20w46a downloaded from Modrinth, which states is compatible with 20w51a on the site.

**To Reproduce**
Run 20w51a with latest Fabric API and Fabric version, and 1.6.1+mc20w46a Mouse Wheelie mod installed.

**Expected behavior**
Game should start without issue.

**Log**
```
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
    at org.multimc.EntryPoint.listen(EntryPoint.java:143)
    at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.RuntimeException: Failed to read accessWidener file from mod amecsapi
    at net.fabricmc.loader.FabricLoader.loadAccessWideners(FabricLoader.java:432)
    at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:131)
    at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
    ... 8 more
Caused by: java.lang.RuntimeException: Namespace (named) does not match current runtime namespace (intermediary)
    at net.fabricmc.accesswidener.AccessWidenerReader.read(AccessWidenerReader.java:47)
    at net.fabricmc.loader.FabricLoader.loadAccessWideners(FabricLoader.java:430)
    ... 10 more
```

Thanks for your help!

**Comment by Siphalor** [comment]
As explained on the Discord it's a random issue with Loom that somehow corrupts 1.17 snapshot builds of this mod. Correctly built versions of this mod have been released.

Thanks for reporting this ;)
