### ISSUE TITLE
[bug] Crash on sorting

### ISSUE THREAD

**Issue by Siphalor** [Siphalor/mouse-wheelie#141]
**Version**
Minecraft: 1.15.2
Fabric Loader: 0.11.7
Fabric API: 0.28.5
Modmenu: 1.10.6
Mouse Wheelie: 1.7.3 

**Describe the bug**
Crash when trying to sort the inventory

**Log**
<details>
<summary>crash report</summary>
<pre><code>
---- Minecraft Crash Report ----
// There are four lights!

Time: 20.09.21 21:08
Description: Unexpected error

java.lang.ArrayStoreException: net.minecraft.class_2960
	at java.util.stream.Nodes$FixedNodeBuilder.accept(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(Unknown Source)
	at java.util.stream.ReferencePipeline.toArray(Unknown Source)
	at de.siphalor.mousewheelie.client.inventory.sort.SortMode$4.sort(SortMode.java:140)
	at de.siphalor.mousewheelie.client.inventory.sort.InventorySorter.sort(InventorySorter.java:109)
	at net.minecraft.class_465.mouseWheelie_triggerSort(class_465.java:812)
	at de.siphalor.mousewheelie.client.keybinding.SortKeyBinding.onPressedPriority(SortKeyBinding.java:38)
	at de.siphalor.amecs.impl.KeyBindingManager.onKeyPressedPriority(KeyBindingManager.java:67)
	at net.minecraft.class_309.handler$zfe000$onKeyPriority(class_309.java:545)
	at net.minecraft.class_309.method_1466(class_309.java:317)
	at net.minecraft.class_309.method_22678(class_309.java:429)
	at net.minecraft.class_1255.execute(class_1255.java:94)
	at net.minecraft.class_309.method_22676(class_309.java:429)
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:98)
	at net.minecraft.class_1041.method_15998(class_1041.java:301)
	at net.minecraft.class_310.method_1523(class_310.java:1012)
	at net.minecraft.class_310.method_1514(class_310.java:619)
	at net.minecraft.client.main.Main.main(Main.java:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Thread: Render thread
Stacktrace:
	at java.util.stream.Nodes$FixedNodeBuilder.accept(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(Unknown Source)
	at java.util.stream.ReferencePipeline.toArray(Unknown Source)
	at de.siphalor.mousewheelie.client.inventory.sort.SortMode$4.sort(SortMode.java:140)
	at de.siphalor.mousewheelie.client.inventory.sort.InventorySorter.sort(InventorySorter.java:109)
	at net.minecraft.class_465.mouseWheelie_triggerSort(class_465.java:812)
	at de.siphalor.mousewheelie.client.keybinding.SortKeyBinding.onPressedPriority(SortKeyBinding.java:38)
	at de.siphalor.amecs.impl.KeyBindingManager.onKeyPressedPriority(KeyBindingManager.java:67)
	at net.minecraft.class_309.handler$zfe000$onKeyPriority(class_309.java:545)
	at net.minecraft.class_309.method_1466(class_309.java:317)
	at net.minecraft.class_309.method_22678(class_309.java:429)
	at net.minecraft.class_1255.execute(class_1255.java:94)
	at net.minecraft.class_309.method_22676(class_309.java:429)
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:98)

-- Affected level --
Details:
	All players: 1 total; [class_746['Pepek112'/264, l='MpServer', x=-207.15, y=69.00, z=-154.30]]
	Chunk stats: Client Chunk Cache: 4761, 481
	Level dimension: minecraft:overworld
	Level name: MpServer
	Level seed: -6638501642157130128
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (-224,69,-207), Chunk: (at 0,4,1 in -14,-13; contains blocks -224,0,-208 to -209,255,-193), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 759 game time, 759 day time
	Known server brands: 
	Level was modded: false
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:450)
	at net.minecraft.class_310.method_1587(class_310.java:1921)
	at net.minecraft.class_310.method_1514(class_310.java:639)
	at net.minecraft.client.main.Main.main(Main.java:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_301, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1782371032 bytes (1699 MB) / 2684354560 bytes (2560 MB) up to 4294967296 bytes (4096 MB)
	CPUs: 12
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		amecsapi: Amecs API 1.1.4+mc1.15.2
		cloth-basic-math: Cloth Basic Math 0.5.0
		cloth-config2: Cloth Config v2 2.14.2
		fabric: Fabric API 0.28.5+1.15
		fabric-api-base: Fabric API Base 0.1.2+9826cad80c
		fabric-biomes-v1: Fabric Biomes (v1) 0.1.6+c1455e800c
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+c1455e800c
		fabric-climbable-api-v1: Fabric Climbable API (v1) 1.0.1+c1455e800c
		fabric-command-api-v1: Fabric Command API (v1) 1.0.3+c1455e800c
		fabric-commands-v0: Fabric Commands (v0) 0.2.1+c1455e800c
		fabric-containers-v0: Fabric Containers (v0) 0.1.4+c1455e800c
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.4+c1455e800c
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+c1455e800c
		fabric-dimensions-v1: fabric-dimensions-v1 0.3.1+c1455e800c
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.1+c1455e800c
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+c1455e800c
		fabric-item-api-v1: Fabric Item API (v1) 1.1.1+c1455e800c
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.1+c1455e800c
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.2+c1455e800c
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+c1455e800c
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+c1455e800c
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.6+c1455e800c
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+c1455e800c
		fabric-models-v0: Fabric Models (v0) 0.1.1+c1455e800c
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.1+c1455e800c
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.4+c1455e800c
		fabric-networking-v0: Fabric Networking (v0) 0.2.1+c1455e800c
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.3.2+c1455e800c
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.6.1+c1455e800c
		fabric-particles-v1: fabric-particles-v1 0.2.2+c1455e800c
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.2+c1455e800c
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.11+c1455e800c
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.3.5+c1455e800c
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.1.1+c1455e800c
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.4+c1455e800c
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.7+c1455e800c
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.1+c1455e800c
		fabric-rendering-v1: Fabric Rendering (v1) 1.2.1+c1455e800c
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.1.11+c1455e800c
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.1.4+c1455e800c
		fabric-textures-v0: Fabric Textures (v0) 1.0.5+c1455e800c
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.4+c1455e800c
		fabricloader: Fabric Loader 0.11.7
		java: Java HotSpot(TM) 64-Bit Server VM 8
		minecraft: Minecraft 1.15.2
		modmenu: Mod Menu 1.10.6
		mousewheelie: Mouse Wheelie 1.7.3+mc1.15.2
		tweed: Tweed 3.0.0-beta.26
</code></pre>
</details>

**Additional context**
Originally reported by Pepek on the official Discord.

**Comment by mannie-exe** [comment]
Hey! I understand this bugfix is probably low-priority since this seems specific to Minecraft version 1.15.x, but I too am getting the same error on sort -- using `v1.7.3-newconfig.3+mc1.15.2`. I'll attempt to submit a PR if I figure this out!

<details>
<summary>Crash Report</summary>

```txt
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 11/2/21, 3:44 PM
Description: Unexpected error

java.lang.ArrayStoreException: net.minecraft.class_2960
	at java.base/java.util.stream.Nodes$FixedNodeBuilder.accept(Nodes.java:1222)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at de.siphalor.mousewheelie.client.inventory.sort.SortMode$4.sort(SortMode.java:140)
	at de.siphalor.mousewheelie.client.inventory.sort.InventorySorter.sort(InventorySorter.java:109)
	at net.minecraft.class_465.mouseWheelie_triggerSort(class_465.java:812)
	at de.siphalor.mousewheelie.client.keybinding.SortKeyBinding.onPressedPriority(SortKeyBinding.java:38)
	at de.siphalor.amecs.impl.KeyBindingManager.onKeyPressedPriority(KeyBindingManager.java:67)
	at net.minecraft.class_312.handler$zfe000$onMouseButtonPriority(class_312.java:533)
	at net.minecraft.class_312.method_1601(class_312.java:78)
	at net.minecraft.class_312.method_22686(class_312.java:150)
	at net.minecraft.class_1255.execute(class_1255.java:104)
	at net.minecraft.class_312.method_22684(class_312.java:150)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:98)
	at net.minecraft.class_1041.method_15998(class_1041.java:375)
	at net.minecraft.class_310.method_1523(class_310.java:1012)
	at net.minecraft.class_310.method_1514(class_310.java:619)
	at net.minecraft.client.main.Main.main(Main.java:204)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/java.util.stream.Nodes$FixedNodeBuilder.accept(Nodes.java:1222)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at de.siphalor.mousewheelie.client.inventory.sort.SortMode$4.sort(SortMode.java:140)
	at de.siphalor.mousewheelie.client.inventory.sort.InventorySorter.sort(InventorySorter.java:109)
	at net.minecraft.class_465.mouseWheelie_triggerSort(class_465.java:812)
	at de.siphalor.mousewheelie.client.keybinding.SortKeyBinding.onPressedPriority(SortKeyBinding.java:38)
	at de.siphalor.amecs.impl.KeyBindingManager.onKeyPressedPriority(KeyBindingManager.java:67)
	at net.minecraft.class_312.handler$zfe000$onMouseButtonPriority(class_312.java:533)
	at net.minecraft.class_312.method_1601(class_312.java:78)
	at net.minecraft.class_312.method_22686(class_312.java:150)
	at net.minecraft.class_1255.execute(class_1255.java:104)
	at net.minecraft.class_312.method_22684(class_312.java:150)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:98)

-- Affected level --
Details:
	All players: 1 total; [class_746['vvizard_'/25132, l='MpServer', x=-204.95, y=63.50, z=-33.19]]
	Chunk stats: Client Chunk Cache: 3025, 2510
	Level dimension: minecraft:overworld
	Level name: MpServer
	Level seed: -2762622409587709235
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (-240,69,-128), Chunk: (at 0,4,0 in -15,-8; contains blocks -240,0,-128 to -225,255,-113), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 169774 game time, 438460 day time
	Known server brands: 
	Level was modded: false
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: true), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: Paper
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:611)
	at net.minecraft.class_310.method_1587(class_310.java:1921)
	at net.minecraft.class_310.method_1514(class_310.java:639)
	at net.minecraft.client.main.Main.main(Main.java:204)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17, Azul Systems, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Azul Systems, Inc.
	Memory: 3735273712 bytes (3562 MB) / 6442450944 bytes (6144 MB) up to 6442450944 bytes (6144 MB)
	CPUs: 16
	JVM Flags: 21 total; -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=32M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms6144m -Xmx6144m
	Fabric Mods: 
		amecsapi: Amecs API 1.1.4+mc1.15.2
		coat: Coat 1.0.0-beta.11
		fabric: Fabric API 0.28.5+1.15
		fabric-api-base: Fabric API Base 0.1.2+28f8190f42
		fabric-biomes-v1: Fabric Biomes (v1) 0.1.6+c1455e800c
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+c1455e800c
		fabric-climbable-api-v1: Fabric Climbable API (v1) 1.0.1+c1455e800c
		fabric-command-api-v1: Fabric Command API (v1) 1.0.3+c1455e800c
		fabric-commands-v0: Fabric Commands (v0) 0.2.1+c1455e800c
		fabric-containers-v0: Fabric Containers (v0) 0.1.4+c1455e800c
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.4+c1455e800c
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+c1455e800c
		fabric-dimensions-v1: fabric-dimensions-v1 0.3.1+c1455e800c
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.1+c1455e800c
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+c1455e800c
		fabric-item-api-v1: Fabric Item API (v1) 1.1.1+c1455e800c
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.1+c1455e800c
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.2+c1455e800c
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+c1455e800c
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+c1455e800c
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.6+c1455e800c
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+c1455e800c
		fabric-models-v0: Fabric Models (v0) 0.1.1+c1455e800c
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.1+c1455e800c
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.4+c1455e800c
		fabric-networking-v0: Fabric Networking (v0) 0.2.1+c1455e800c
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.3.2+c1455e800c
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.6.1+c1455e800c
		fabric-particles-v1: fabric-particles-v1 0.2.2+c1455e800c
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.2+c1455e800c
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.11+c1455e800c
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.3.5+c1455e800c
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.1.1+c1455e800c
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.4+c1455e800c
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.7+c1455e800c
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.1+c1455e800c
		fabric-rendering-v1: Fabric Rendering (v1) 1.2.1+c1455e800c
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.1.11+c1455e800c
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.1.4+c1455e800c
		fabric-textures-v0: Fabric Textures (v0) 1.0.5+c1455e800c
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.4+c1455e800c
		fabricloader: Fabric Loader 0.11.7
		java: OpenJDK 64-Bit Server VM 17
		me_hypherionmc_simple-rpc-lib: simple-rpc-lib 2.1.5
		minecraft: Minecraft 1.15.2
		mm: Manningham Mills 2.0
		modmenu: Mod Menu 1.10.6
		mousewheelie: Mouse Wheelie 1.7.3-newconfig.3+mc1.15.2
		optifabric: Optifabric 1.0.1
		org_slf4j_slf4j-api: slf4j-api 1.7.30
		org_slf4j_slf4j-simple: slf4j-simple 1.7.30
		org_zeroturnaround_zt-zip: zt-zip 1.14
		simple-rpc: Simple Discord RPC 1.15.2-2.3.1-fabric
		tweed4_annotated: tweed4_annotated 1.2.0
		tweed4_base: tweed4_base 1.3.1
		tweed4_data: tweed4_data 1.2.0
		tweed4_data_hjson: tweed4_data_hjson 1.1.0
		tweed4_tailor_coat: tweed4_tailor_coat 1.0.1
		tweed4_tailor_screen: tweed4_tailor_screen 1.0.1
		worldedit: WorldEdit 7.1.0;8e55131
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce RTX 2070 SUPER/PCIe/SSE2 GL version 4.6.0 NVIDIA 496.49, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: optifine
	Current Language: English (US)
	CPU: 16x AMD Ryzen 7 5800X 8-Core Processor 
	OptiFine Version: OptiFine_1.15.2_HD_U_G6
	OptiFine Build: 20210124-205244
	Render Distance Chunks: 24
	Mipmaps: 1
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: BSL_v8.1.01
	OpenGlVersion: 4.6.0 NVIDIA 496.49
	OpenGlRenderer: NVIDIA GeForce RTX 2070 SUPER/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 16
```
</details>
