### ISSUE TITLE
[bug] Crash on world join

### ISSUE THREAD

**Issue by ChloeDawn** [Siphalor/mouse-wheelie#160]
**Version**
1.8.3+mc1.18.2
**Describe the bug**
The game crashes when opening a singleplayer world

**To Reproduce**
1. Launch the game
2. Open a world

**Expected behavior**
The world should load without crashing

**Log**
```
Unreported exception thrown!
java.lang.NoClassDefFoundError: de/siphalor/tweed4/tailor/DropdownMaterial
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:223)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:174)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at de.siphalor.mousewheelie.MWConfig$Sort.<init>(MWConfig.java:89)
	at de.siphalor.mousewheelie.MWConfig.<clinit>(MWConfig.java:85)
	at net.minecraft.class_1703.handler$zja000$onSlotUpdate(class_1703.java:914)
	at net.minecraft.class_1703.method_7610(class_1703.java:594)
	at net.minecraft.class_634.method_11153(class_634.java:1052)
	at net.minecraft.class_2649.method_11439(class_2649.java:44)
	at net.minecraft.class_2649.method_11054(class_2649.java:11)
	at net.minecraft.class_2600.method_11072(class_2600.java:22)
	at net.minecraft.class_1255.method_18859(class_1255.java:157)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:131)
	at net.minecraft.class_1255.method_5383(class_1255.java:116)
	at net.minecraft.class_310.method_1523(class_310.java:1085)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ClassNotFoundException: de.siphalor.tweed4.tailor.DropdownMaterial
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:158)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 29 more
```

**Additional context**
Loaded mods:
```
	- amecsapi 1.3.5+mc22w06a via mousewheelie
	- cloth-basic-math 0.6.0 via cloth-config
	- cloth-config 6.2.57
	- coat 1.0.0-beta.17+mc1.18.2 via mousewheelie
	- continuity 1.1.0+1.18.2
	- fabric-api-base 0.4.3+d7c144a8d2 via mousewheelie
	- fabric-events-interaction-v0 0.4.18+d7c144a8d2 via mousewheelie
	- fabric-item-api-v1 1.3.2+691a79b5d2 via mousewheelie
	- fabric-key-binding-api-v1 1.0.11+54e5b2ecd2 via iris
	- fabric-lifecycle-events-v1 2.0.1+25407454d2 via mousewheelie
	- fabric-networking-api-v1 1.0.20+d882b915d2 via mousewheelie
	- fabric-renderer-api-v1 0.4.13+d882b91560
	- fabric-rendering-data-attachment-v1 0.3.6+d7c144a8d2 via sodium
	- fabric-rendering-fluids-v1 2.0.1+54e5b2ecd2 via sodium
	- fabric-resource-loader-v0 0.4.16+55dca1a4d2 via iris
	- fabricloader 0.13.3
	- indium 1.0.2+mc1.18.2
	- infinitemusic 1.5.1
	- iris 1.2.2-build.32
	- java 17
	- lazydfu 0.1.2
	- minecraft 1.18.2
	- morechathistory 1.1.0
	- mousewheelie 1.8.3+mc1.18.2
	- org_anarres_jcpp 1.4.14 via iris
	- org_joml_joml 1.10.2 via sodium
	- sodium 0.4.1+build.15
	- tweed4_data 1.2.1+mc1.18.2 via mousewheelie
	- tweed4_data_hjson 1.1.0+mc1.18.2 via mousewheelie
```

**Comment by Siphalor** [comment]
Hi, thanks for reporting this bug.

The list of loaded mods that you posted doesn't really make a lot of sense since that version of Mouse Wheelie bundles some more library mods that don't seem to be loaded for you.

Did this issue happen more than once? If so, please try to delete the `.fabric` folder in your Minecraft instance folder.

Just to be sure, can you also try out the latest release (1.8.4)? It shouldn't touch anything about this, but since this issue is pretty weird, I'd give it a try anyway.

**Comment by ChloeDawn** [comment]
Still experiencing the same crash after deleting `.fabric` and updating to `1.8.4`

**Comment by Siphalor** [comment]
Can you hash the Mouse Wheelie jar you downloaded?

I just want to confirm that the files you downloaded are intact.

**Comment by Jazztache** [comment]
I can also confirm that this bug is also on `1.8.7`. 
Steps to reproduce:
- Put in the mod file
- Moved other mods
- Deleted .fabric
- Jumped into an existing world
- Crash with exit code 255 with the same error above.

**Comment by ChloeDawn** [comment]
I tried reproducing with nothing but version `1.8.7` installed in a new instance using Fabric Loader `0.13.3`.
It gave me a different stacktrace upon trying to create a world, unsure if related issue.
```
Name: mousewheelie-1.8.7+mc1.18.2.jar
Size: 816396 bytes (797 KiB)
SHA256: 5e69323587ac07fb3d487289bfb49b48cf6a462632bb86fdfc33fdac4c5da4d0
```
```
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 27/03/2022, 02:56
Description: Unexpected error

java.lang.NoClassDefFoundError: Could not initialize class de.siphalor.mousewheelie.MWConfig
	at de.siphalor.mousewheelie.client.keybinding.ScrollKeyBinding.onPressedPriority(ScrollKeyBinding.java:39)
	at de.siphalor.amecs.impl.KeyBindingManager.lambda$onKeyPressedPriority$5(KeyBindingManager.java:160)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
	at de.siphalor.amecs.impl.KeyBindingManager.onKeyPressedPriority(KeyBindingManager.java:160)
	at net.minecraft.class_312.handler$zzh000$onMouseScroll(class_312.java:634)
	at net.minecraft.class_312.method_1598(class_312.java:125)
	at net.minecraft.class_312.method_22687(class_312.java:166)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_312.method_22685(class_312.java:166)
	at org.lwjgl.glfw.GLFWScrollCallbackI.callback(GLFWScrollCallbackI.java:37)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:204)
	at net.minecraft.class_1041.method_15998(class_1041.java:310)
	at net.minecraft.class_310.method_1523(class_310.java:1147)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at de.siphalor.mousewheelie.client.keybinding.ScrollKeyBinding.onPressedPriority(ScrollKeyBinding.java:39)
	at de.siphalor.amecs.impl.KeyBindingManager.lambda$onKeyPressedPriority$5(KeyBindingManager.java:160)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
	at de.siphalor.amecs.impl.KeyBindingManager.onKeyPressedPriority(KeyBindingManager.java:160)
	at net.minecraft.class_312.handler$zzh000$onMouseScroll(class_312.java:634)
	at net.minecraft.class_312.method_1598(class_312.java:125)
	at net.minecraft.class_312.method_22687(class_312.java:166)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_312.method_22685(class_312.java:166)
	at org.lwjgl.glfw.GLFWScrollCallbackI.callback(GLFWScrollCallbackI.java:37)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:204)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods
Stacktrace:
	at net.minecraft.class_6360.method_36565(class_6360.java:49)
	at net.minecraft.class_310.method_1587(class_310.java:2383)
	at net.minecraft.class_310.method_1514(class_310.java:761)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 668991488 bytes (638 MiB) / 4294967296 bytes (4096 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
	Identifier: Intel64 Family 6 Model 60 Stepping 3
	Microarchitecture: Haswell (Client)
	Frequency (GHz): 4.00
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce GTX 970
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x13c2
	Graphics card #0 versionInfo: DriverVersion=30.0.15.1123
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 1.33
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 1.33
	Memory slot #1 type: DDR3
	Memory slot #2 capacity (MB): 8192.00
	Memory slot #2 clockSpeed (GHz): 1.33
	Memory slot #2 type: DDR3
	Memory slot #3 capacity (MB): 8192.00
	Memory slot #3 clockSpeed (GHz): 1.33
	Memory slot #3 type: DDR3
	Virtual memory max (MB): 37579.97
	Virtual memory used (MB): 19252.50
	Swap memory total (MB): 4864.00
	Swap memory used (MB): 235.16
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4G -XX:+UseZGC
	Launched Version: fabric-loader-0.13.3-1.18.2
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce GTX 970/PCIe/SSE2 GL version 3.2.0 NVIDIA 511.23, NVIDIA Corporation
	Window size: 854x480
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: Fabric Mods
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
```

As in the original report, some of the embedded mods are not listed as loaded at the time of the crash, which leads me to believe that this is an exception caused by a suppressed embedded mod loading exception. I will try extracting the mods so that they are explicitly loaded.

Update: Found the cause! An embedded dependency has an unresolved dependency.
```
Mod 'tweed4_base' (tweed4_base) 1.4.3+mc1.18.2 requires any version of fabric-registry-sync-v0, which is missing!
```

After installing `fabric-registry-sync-v0`, the mod is now functioning normally.

**Comment by Siphalor** [comment]
Thank you very much for finding the cause of this.
For Minecraft 1.18.2 `fabric-registry-sync-v0` is indeed a required dependency that I somehow missed from embedding in Mouse Wheelie.
I think it worked before because I erroneously embedded it directly in `tweed4_base`.

A release with a fix is coming soon :)
