### ISSUE TITLE
Unable to join my own server when using mouse wheelie

### ISSUE THREAD

**Issue by Regular-Baf** [Siphalor/mouse-wheelie#163]
From what I can tell, it tries to request some config or something. I've never really had any issues with it before and without the mod it all seems to work fine. Oddly enough though, I found joining Hypixel to work so, my best guess is that something isn't compatible.

Here's the part of the log from when I tried joining
```
[06:25:10] [User Authenticator #4/INFO]: UUID of player Mr_Melon_Masher is e660f343-90e4-4c6a-9a44-a85ef3aa225b                                                                                                   
[06:25:11] [Server thread/INFO]: Mr_Melon_Masher[/192.168.1.7:38784] logged in with entity id 274 at (603.9573810376835, 64.0, -830.9002868004767)                                                                
[06:25:11] [Server thread/INFO]: Mr_Melon_Masher joined the game                                                                                                                                                  
[06:25:12] [Netty Epoll Server IO #3/ERROR]: Encountered exception while handling in channel with name "tweed4:request_sync"                                                                                      
io.netty.handler.codec.DecoderException: Requested sync for unknown config file: mousewheelie                                                                                                                     
        at de.siphalor.tweed4.Tweed.lambda$onInitialize$0(Tweed.java:89) ~[tweed4_base-1.4.2+mc1.18.2-d58ef64dbc9bb756.jar:?]                                                                                     
        at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.receive(ServerPlayNetworkAddon.java:89) ~[fabric-networking-api-v1-1.0.21+d882b91560-a8c4d1390f5e44a7.jar:?]                         
        at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.receive(ServerPlayNetworkAddon.java:38) ~[fabric-networking-api-v1-1.0.21+d882b91560-a8c4d1390f5e44a7.jar:?]                         
        at net.fabricmc.fabric.impl.networking.AbstractChanneledNetworkAddon.handle(AbstractChanneledNetworkAddon.java:100) [fabric-networking-api-v1-1.0.21+d882b91560-a8c4d1390f5e44a7.jar:?]                   
        at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.handle(ServerPlayNetworkAddon.java:84) [fabric-networking-api-v1-1.0.21+d882b91560-a8c4d1390f5e44a7.jar:?]                           
        at net.minecraft.class_3244.handler$zhj000$handleCustomPayloadReceivedAsync(class_3244.java:1714) [server-intermediary.jar:?]                                                                             
        at net.minecraft.class_3244.method_12075(class_3244.java) [server-intermediary.jar:?]                                                                                                                     
        at net.minecraft.class_2817.method_12199(class_2817.java:38) [server-intermediary.jar:?]                                                                                                                  
        at net.minecraft.class_2817.method_11054(class_2817.java:7) [server-intermediary.jar:?]                                                                                                                   
        at net.minecraft.class_2535.method_10759(class_2535.java:172) [server-intermediary.jar:?]                                                                                                                 
        at net.minecraft.class_2535.method_10770(class_2535.java:157) [server-intermediary.jar:?]                                                                                                                 
        at net.minecraft.class_2535.channelRead0(class_2535.java:55) [server-intermediary.jar:?]                                                                                                                  
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) [netty-all-4.1.68.Final.jar:?]                                                                           
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:?]                                                                
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:?]                                                                
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar:?]                                                                  
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [netty-all-4.1.68.Final.jar:?]                                                                              
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) [netty-all-4.1.68.Final.jar:?]                                                                                  
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:?]                                                                
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:?]                                                                
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar:?]                                                                  
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [netty-all-4.1.68.Final.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) [netty-all-4.1.68.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [netty-all-4.1.68.Final.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) [netty-all-4.1.68.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar:?]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [netty-all-4.1.68.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar:?]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [netty-all-4.1.68.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar:?]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-all-4.1.68.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:?]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-all-4.1.68.Final.jar:?]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795) [netty-all-4.1.68.Final.jar:?]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480) [netty-all-4.1.68.Final.jar:?]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) [netty-all-4.1.68.Final.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [netty-all-4.1.68.Final.jar:?]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.68.Final.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
[06:25:12] [Server thread/INFO]: Mr_Melon_Masher lost connection: Internal Exception: io.netty.handler.codec.DecoderException: Requested sync for unknown config file: mousewheelie
[06:25:12] [Server thread/INFO]: Mr_Melon_Masher left the game
[06:25:13] [Server thread/WARN]: handleDisconnection() called twice
```
My client uses these mods: https://github.com/Regular-Baf/bafwiz
My server uses these mods: https://github.com/Regular-Baf/bafserve

**Comment by Siphalor** [comment]
Thank you for the report.

The bug is a critical issue in my config library, that's also on the server because of Wandering Collector.
I'm sitting on a fix and will try to push out a fix for all affected mods as soon as possible.

A temporary workaround will be to install Mouse Wheelie on your server, or to remove Mouse Wheelie/Wandering Collector.
