### ISSUE TITLE
[bug] Minecraft crashes when loading map while using mousewheelie-1.10.7+mc1.19.4

### ISSUE THREAD

**Issue by LeYoshi05** [Siphalor/mouse-wheelie#226]
**Version**
1.19.4; mousewheelie-1.10.7+mc1.19.4

**Describe the bug**
When I try to join any singleplayer world or server, my game crashes.

**To Reproduce**
Simply start the game with MouseWheelie and Fabric

**Expected behavior**
The game running normally

**Log**

```
---- Minecraft Crash Report ----
// Why did you do that?

Time: 2023-05-22 21:09:54
Description: Unexpected error

java.lang.IllegalAccessError: class de.siphalor.mousewheelie.client.util.CreativeSearchOrder tried to access private field net.minecraft.class_7706.field_40200 (de.siphalor.mousewheelie.client.util.CreativeSearchOrder and net.minecraft.class_7706 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @62e136d3)
	at de.siphalor.mousewheelie.client.util.CreativeSearchOrder.refreshItemSearchPositionLookup(CreativeSearchOrder.java:66)
	at de.siphalor.mousewheelie.client.MWClient.lambda$onInitializeClient$1(MWClient.java:97)
	at net.fabricmc.fabric.api.client.networking.v1.ClientPlayConnectionEvents.lambda$static$2(ClientPlayConnectionEvents.java:50)
	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.onServerReady(ClientPlayNetworkAddon.java:70)
	at net.minecraft.class_634.handler$zcm000$fabric-networking-api-v1$handleServerPlayReady(class_634.java:2736)
	at net.minecraft.class_634.method_11120(class_634.java:463)
	at net.minecraft.class_2678.method_11567(class_2678.java:92)
	at net.minecraft.class_2678.method_11054(class_2678.java:25)
	at net.minecraft.class_2600.method_11072(class_2600.java:40)
	at net.optifine.util.PacketRunnable.run(PacketRunnable.java:28)
	at net.minecraft.class_1255.method_18859(class_1255.java:198)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:163)
	at net.minecraft.class_1255.method_5383(class_1255.java:140)
	at net.minecraft.class_310.method_1523(class_310.java:1174)
	at net.minecraft.class_310.method_1514(class_310.java:801)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at de.siphalor.mousewheelie.client.util.CreativeSearchOrder.refreshItemSearchPositionLookup(CreativeSearchOrder.java:66)
	at de.siphalor.mousewheelie.client.MWClient.lambda$onInitializeClient$1(MWClient.java:97)
	at net.fabricmc.fabric.api.client.networking.v1.ClientPlayConnectionEvents.lambda$static$2(ClientPlayConnectionEvents.java:50)
	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.onServerReady(ClientPlayNetworkAddon.java:70)
	at net.minecraft.class_634.handler$zcm000$fabric-networking-api-v1$handleServerPlayReady(class_634.java:2736)
	at net.minecraft.class_634.method_11120(class_634.java:463)
	at net.minecraft.class_2678.method_11567(class_2678.java:92)
	at net.minecraft.class_2678.method_11054(class_2678.java:25)
	at net.minecraft.class_2600.method_11072(class_2600.java:40)
	at net.optifine.util.PacketRunnable.run(PacketRunnable.java:28)
	at net.minecraft.class_1255.method_18859(class_1255.java:198)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:163)

-- Affected level --
Details:
	All players: 1 total; [class_746['LeYoshi05'/1268424, l='ClientLevel', x=8.50, y=65.00, z=8.50]]
	Chunk stats: 729, 0
	Level dimension: minecraft:overworld
	Level spawn location: World: (8,64,8), Section: (at 8,0,8 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 0 game time, 0 day time
	Server brand: ~~NULL~~
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:583)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:825)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, file/LeGhastCity TP, Fabric Mods, file/Fullbright.zip

-- System Details --
Details:
	Minecraft Version: 1.19.4
	Minecraft Version ID: 1.19.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 354105296 bytes (337 MiB) / 805306368 bytes (768 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: 12th Gen Intel(R) Core(TM) i5-12400
	Identifier: Intel64 Family 6 Model 151 Stepping 2
	Microarchitecture: Alder Lake
	Frequency (GHz): 2.50
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: Intel(R) UHD Graphics 730
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x4682
	Graphics card #0 versionInfo: DriverVersion=30.0.101.1273
	Graphics card #1 name: NVIDIA GeForce RTX 3050
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 4095.00
	Graphics card #1 deviceId: 0x2507
	Graphics card #1 versionInfo: DriverVersion=31.0.15.3118
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 36637.87
	Virtual memory used (MB): 17938.29
	Swap memory total (MB): 20480.00
	Swap memory used (MB): 372.79
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: fabric-loader-0.14.19-1.19.4
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce RTX 3050/PCIe/SSE2 GL version 3.2.0 NVIDIA 531.18, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla
	Current Language: en_us
	CPU: 12x 12th Gen Intel(R) Core(TM) i5-12400
	OptiFine Version: OptiFine_1.19.4_HD_U_I4
	OptiFine Build: 20230408-043701
	Render Distance Chunks: 29
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: (internal)
	OpenGlVersion: 3.2.0 NVIDIA 531.18
	OpenGlRenderer: NVIDIA GeForce RTX 3050/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12

-- OptiFabric --
Details:
	OptiFine jar designed for: 1.19.4
	OptiFine jar version: OptiFine_1.19.4_HD_U_I4
	OptiFine jar status: Valid OptiFine installer
	OptiFine remapped jar: C:/Users/yoshi/AppData/Roaming/.minecraft/.optifine/OptiFine_1.19.4_HD_U_I4/Optifine-mapped.jar
	OptiFabric error: <None>
```

**Additional context**
When starting the game in version 1.19.2 with MouseWheelie "mousewheelie-1.10.2+mc1.19-pre1.jar", the game works normally.
Also, no 1.19.4 versions of MouseWheelie work when using Fabric 1.19.4. I've tried multiple versions. Also, I've tried reinstalling Fabric.

**Comment by Siphalor** [comment]
Thanks for the report :)

As a temporary workaround you can install Fabric API‌ alongside.
The fix isn't too complicated though, so a fixed release will be published soon™ as well.
