### ISSUE TITLE
[bug] crash with refill sound

### ISSUE THREAD

**Issue by A5ho9999** [Siphalor/mouse-wheelie#251]
**Version**
Fabric: 0.14.22
Minecraft: 1.20.1
Mod version: https://modrinth.com/mod/mouse-wheelie/version/1.13.0+mc1.20.1

**Describe the bug**
Game will randomly crash when refill sound is played and subtitles are enabled. This could also be connected/partnered with using [accurate block placement](https://modrinth.com/mod/accurate-block-placement-reborn) and placing blocks faster than the refill can keep up with/play

**To Reproduce**
Hard to reproduce as it's very random and happens rarely. I was only able to re-create it a couple times by doing this.
1. Have refill + refill sound & subtitles on
2. Fill your hud with a couple of the same blocks
3. Spin around in a circle will holding place (using above mod will place them fast enough to spin around without having to spam)
4. Repeat until crashes (took me somewhere between 10 to 50 attempts to re-create)

**Expected behavior**
Not crash

**Log**
Using [Stack Deobfuscator](https://modrinth.com/mod/stackdeobf)
```
java.util.ConcurrentModificationException
at java.base@18.0.2/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013)
at java.base@18.0.2/java.util.ArrayList$Itr.next(ArrayList.java:967)
at MC//net.minecraft.client.gui.hud.SubtitlesHud.render(SubtitlesHud.java:60)
at MC//net.minecraft.client.gui.hud.InGameHud.render(InGameHud.java:335)
at MC//net.minecraft.client.render.GameRenderer.render(GameRenderer.java:926)
at MC//net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1219)
at MC//net.minecraft.client.MinecraftClient.run(MinecraftClient.java:802)
at net.minecraft.client.main.Main.main(Main.java:250)
at app//net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
at app//net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
at app//net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

Full Log: https://gist.github.com/A5ho9999/773952b310231d211f264d9f4e6287fc

**Additional context**
I wasn't able to create when refill sound was toggled off or when subtitles were also off, despite trying each 50+ times with method above.

**Comment by LxkasDEV** [comment]
I was able to reproduce this bug multiple times in 1.20.2 (every mod-version for 1.20.2) without subtitles
