### ISSUE TITLE
[bug]  mouse wheelie broken in 1.20.5

### ISSUE THREAD

**Issue by ImUrX** [Siphalor/mouse-wheelie#261]
**Version**
1.20.5

**Log**
The important parts of the log.
```
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'mousewheelie'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:484)
	at net.minecraft.client.main.Main.main(Main.java:223)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
	Suppressed: java.lang.NoClassDefFoundError: net/fabricmc/fabric/api/networking/v1/FabricPacket
		at java.base/java.lang.ClassLoader.defineClass1(Native Method)
		at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027)
		at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
		at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:160)
		at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355)
		at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
		at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
		at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
		at de.siphalor.tweed4.Tweed.onInitialize(Tweed.java:86)
		at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
		... 9 more
	Caused by: java.lang.ClassNotFoundException: net.fabricmc.fabric.api.networking.v1.FabricPacket
		at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
		at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
		at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
		at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
		at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
		... 19 more
Caused by: java.lang.NoClassDefFoundError: net/fabricmc/fabric/api/networking/v1/ServerPlayNetworking$PlayChannelHandler
	at de.siphalor.mousewheelie.common.network.MWLogicalServerNetworking.setup(MWLogicalServerNetworking.java:48)
	at de.siphalor.mousewheelie.MouseWheelie.onInitialize(MouseWheelie.java:39)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
	... 9 more
Caused by: java.lang.ClassNotFoundException: net.fabricmc.fabric.api.networking.v1.ServerPlayNetworking$PlayChannelHandler
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 12 more
```

**Comment by 1divided0** [comment]
Same error message in 1.20.6

**Comment by Siphalor** [comment]
There is now a beta version available that supports these versions :)
