### ISSUE TITLE
[bug] Crash on game start (1.2.5, 1.14.4)

### ISSUE THREAD

**Issue by Madis0** [Siphalor/mouse-wheelie#27]
**Version**
1.14.4, 1.2.5
**Describe the bug**
Game crashes on start.

**To Reproduce**
Open the game with Fabric API 0.3.0 b 200 and MouseWheelie 1.2.5.

**Expected behavior**
Game would run.

**Log**
```
---- Minecraft Crash Report ----
// Would you like a cupcake?

Time: 22.07.19 11:01
Description: Initializing game

java.lang.NoClassDefFoundError: de/siphalor/amecs/api/AmecsKeyBinding
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:45)
	at net.fabricmc.loader.EntrypointStorage$NewEntry.create(EntrypointStorage.java:101)
	at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:93)
	at net.fabricmc.loader.EntrypointStorage.getEntrypoints(EntrypointStorage.java:140)
	at net.fabricmc.loader.FabricLoader.getEntrypoints(FabricLoader.java:186)
	at net.fabricmc.loader.entrypoint.hooks.EntrypointClient.start(EntrypointClient.java:35)
	at net.minecraft.class_310.method_1503(class_310.java)
	at net.minecraft.class_310.method_1514(class_310.java:394)
	at net.minecraft.client.main.Main.main(Main.java:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:129)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
Caused by: java.lang.ClassNotFoundException: de.siphalor.amecs.api.AmecsKeyBinding
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:160)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 18 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:45)
	at net.fabricmc.loader.EntrypointStorage$NewEntry.create(EntrypointStorage.java:101)
	at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:93)
	at net.fabricmc.loader.EntrypointStorage.getEntrypoints(EntrypointStorage.java:140)
	at net.fabricmc.loader.FabricLoader.getEntrypoints(FabricLoader.java:186)
	at net.fabricmc.loader.entrypoint.hooks.EntrypointClient.start(EntrypointClient.java:35)
	at net.minecraft.class_310.method_1503(class_310.java)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.class_310.method_1514(class_310.java:394)
	at net.minecraft.client.main.Main.main(Main.java:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:129)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Linux (amd64) version 4.19.59-1-MANJARO
	Java Version: 1.8.0_222, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1010679968 bytes (963 MB) / 1342177280 bytes (1280 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 7 total; -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		cloth-config2: Cloth Config v2 0.2.0
		com_github_siphalor_amecs: amecs 1.1.0
		fabric: Fabric API 0.3.0+build.200
		fabric-api-base: fabric-api-base 0.1.0+5914746342
		fabric-biomes-v1: fabric-biomes-v1 0.1.0+896c7fbb42
		fabric-commands-v0: fabric-commands-v0 0.1.1+25fd0c5242
		fabric-containers-v0: fabric-containers-v0 0.1.2+25fd0c5242
		fabric-content-registries-v0: fabric-content-registries-v0 0.1.1+05f11b7542
		fabric-crash-report-info-v1: fabric-crash-report-info-v1 0.1.0+5914746342
		fabric-events-interaction-v0: fabric-events-interaction-v0 0.1.0+ea100f6142
		fabric-events-lifecycle-v0: fabric-events-lifecycle-v0 0.1.0+5914746342
		fabric-item-groups-v0: fabric-item-groups-v0 0.1.0+1e69a0a542
		fabric-keybindings: fabric-keybindings 0.1.0+93af775a
		fabric-keybindings-v0: fabric-keybindings-v0 0.1.1+7dfef87c42
		fabric-loot-tables-v1: fabric-loot-tables-v1 0.1.0+43028fa642
		fabric-mining-levels-v0: fabric-mining-levels-v0 0.1.0+59147463
		fabric-models-v0: fabric-models-v0 0.1.0+5914746342
		fabric-networking-blockentity-v0: fabric-networking-blockentity-v0 0.1.1+25fd0c5242
		fabric-networking-v0: fabric-networking-v0 0.1.2+ea100f6142
		fabric-object-builders-v0: fabric-object-builders-v0 0.1.1+592d1d2242
		fabric-registry-sync-v0: fabric-registry-sync-v0 0.2.2+ea100f6142
		fabric-renderer-api-v1: fabric-renderer-api-v1 0.1.1+9486cfbf42
		fabric-renderer-indigo: fabric-renderer-indigo 0.1.9+9486cfbf42
		fabric-rendering-data-attachment-v1: fabric-rendering-data-attachment-v1 0.1.0+02a46d5b42
		fabric-rendering-fluids-v1: fabric-rendering-fluids-v1 0.1.0+dc4c57c242
		fabric-rendering-v0: fabric-rendering-v0 0.1.1+6dad974e42
		fabric-resource-loader: fabric-resource-loader 0.1.0+93af775a
		fabric-resource-loader-v0: fabric-resource-loader-v0 0.1.1+5914746355
		fabric-tag-extensions-v0: fabric-tag-extensions-v0 0.1.1+c189dc5c55
		fabric-textures-v0: fabric-textures-v0 0.1.4+792c1c3542
		fabricloader: Fabric Loader 0.4.8+build.155
		mousewheelie: Mouse Wheelie 1.2.5+1.14.4
		tweed: Tweed API 2.2.0-beta.5
	Launched Version: fabric-loader-0.4.8+build.155-1.14.4
	LWJGL: 3.2.2 build 10
	OpenGL: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: ~~ERROR~~ NullPointerException: null
	Current Language: ~~ERROR~~ NullPointerException: null
	CPU: <unknown>
```

**Additional context**
N/A

**Comment by Siphalor** [comment]
I published a hot fix :)
