### ISSUE TITLE
Crash on version 1.1.0+1.14

### ISSUE THREAD

**Issue by luffymoreno** [Siphalor/mouse-wheelie#3]
When scroll down or up in an empty slot it crashes the game

---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 4/30/19 2:40 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.minecraft.class_513.method_2625(class_513.java:81)
	at net.minecraft.class_513.callRefreshResultButtons(class_513.java)
[crash-2019-04-30_14.36.05-client.txt](https://github.com/Siphalor/mouse-wheelie/files/3132441/crash-2019-04-30_14.36.05-client.txt)

	at net.minecraft.class_507.mouseWheelie_scrollRecipeBook(class_507.java:617)
	at net.minecraft.class_490.mouseWheelie_onMouseScrollRecipeBook(class_490.java:525)
	at net.minecraft.class_312.handler$onMouseScrolled$zbg001(class_312.java:1038)
	at net.minecraft.class_312.method_1598(class_312.java:120)
	at net.minecraft.class_312$$Lambda$1680/1034673425.invoke(Unknown Source)
	at org.lwjgl.glfw.GLFWScrollCallbackI.callback(GLFWScrollCallbackI.java:37)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3050)
	at net.minecraft.class_1041.method_16001(class_1041.java:425)
	at net.minecraft.class_1041.method_15998(class_1041.java:283)
	at net.minecraft.class_310.method_15994(class_310.java:1023)
	at net.minecraft.class_310.method_1523(class_310.java:976)
	at net.minecraft.class_310.method_1514(class_310.java:411)
	at net.minecraft.client.main.Main.main(Main.java:154)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:127)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.class_513.method_2625(class_513.java:81)
	at net.minecraft.class_513.callRefreshResultButtons(class_513.java)
	at net.minecraft.class_507.mouseWheelie_scrollRecipeBook(class_507.java:617)
	at net.minecraft.class_490.mouseWheelie_onMouseScrollRecipeBook(class_490.java:525)
	at net.minecraft.class_312.handler$onMouseScrolled$zbg001(class_312.java:1038)
	at net.minecraft.class_312.method_1598(class_312.java:120)
	at net.minecraft.class_312$$Lambda$1680/1034673425.invoke(Unknown Source)
	at org.lwjgl.glfw.GLFWScrollCallbackI.callback(GLFWScrollCallbackI.java:37)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3050)
	at net.minecraft.class_1041.method_16001(class_1041.java:425)
	at net.minecraft.class_1041.method_15998(class_1041.java:283)

-- Affected level --
Details:
	Level name: MpServer
	All players: 2 total; [class_746['Nutria1'/5297, l='MpServer', x=191.90, y=68.00, z=1409.92], class_745['buenajuan300'/68, l='MpServer', x=192.28, y=69.00, z=1411.60]]
	Chunk stats: MultiplayerChunkCache: 729, 462
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (112,84,-112), Chunk: (at 0,5,0 in 7,-7; contains blocks 112,0,-112 to 127,255,-97), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 77008 game time, 106002 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: fabric
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:421)
	at net.minecraft.class_310.method_1587(class_310.java:1920)
	at net.minecraft.class_310.method_1514(class_310.java:431)
	at net.minecraft.client.main.Main.main(Main.java:154)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:127)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

**Comment by Siphalor** [comment]
Can you give exact instructions on how to reproduce that bug?

**Comment by luffymoreno** [comment]
mouse wheel up and then mousewheel down or viceverse in an empty slot of
the player's inventory

**Comment by luffymoreno** [comment]
mouse wheel up and then mousewheel down or viceverse in an empty slot of the player's inventory

**Comment by NinjaPhenix** [comment]
Made a PR with a bit more infomation about this Issue, https://github.com/Siphalor/mouse-wheelie/pull/5

**Comment by Siphalor** [comment]
Thanks to NinjaPhoenix, it's fixed
